services:
  db:
    image: postgres:13.1
    environment:
      POSTGRES_DB: todo                   # Ensure this matches the database name
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate:v4.14.1
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations         # Ensure migrations files are in a ./migrations directory
    command: ["-path", "/migrations", "-database", "postgres://user:password@db:5432/todo?sslmode=disable", "up"]
