/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface SchemaMigrations {
  dirty: boolean;
  version: Int8;
}

export interface Todos {
  created_at: Generated<Timestamp | null>;
  description: string | null;
  id: Generated<number>;
  is_completed: Generated<boolean | null>;
  title: string;
  updated_at: Generated<Timestamp | null>;
}

export interface DB {
  schema_migrations: SchemaMigrations;
  todos: Todos;
}
